name: Run Jira Lint

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Checkout External Repository
      uses: actions/checkout@v2
      with:
        repository: 'HopetonFactory/jira-lint'
        token: ${{ secrets.JIRA_LINT_ACCESS_TOKEN }}
        path: 'jira-lint'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies with Poetry
      run: |
        cd jira-lint
        poetry install

    - name: Run Python program
      run: |
        cd jira-lint
        poetry run python jira_lint/main.py --api-key ${{ secrets.JIRA_API_TOKEN }} --jira-user ${{ secrets.JIRA_USER }}
