name: Jira Lint

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-jira-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add SSH key to the agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.JIRA_LINT_DEPLOY_KEY }}

    - name: Checkout External Repository
      uses: actions/checkout@v3
      with:
        repository: 'HopetonFactory/jira-lint'
        ref: 'main'
        path: 'jira-lint'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies with Poetry
      run: |
        cd jira-lint
        poetry install

    - name: Run Python program
      run: |
        cd jira-lint
        poetry run python jira_lint/main.py --api-key ${{ secrets.JIRA_API_TOKEN }} --jira-user ${{ secrets.JIRA_USER }}
